name = "cerqueira-fullstack"
compatibility_date = "2024-07-25"

pages_build_output_dir = ".next"

# Add this section
[build]
command = "npm run build:cf"

# Add this line to enable Node.js compatibility
compatibility_flags = ["nodejs_compat"]