name = "cerqueira_fullstack"
compatibility_date = "2024-07-25"

pages_build_output_dir = ".vercel/output/static"

# Add this line to enable Node.js compatibility
compatibility_flags = ["nodejs_compat"]