# wrangler.toml

name = "cerqueira"
compatibility_date = "2024-07-25"

# This is the ONLY required setting for a Next.js Pages project.
# It tells Cloudflare where to find your static files after the build.
pages_build_output_dir = ".vercel/output/static"