name = "cerqueira"
compatibility_date = "2024-07-25"

# Worker script configuration
main = "worker/index.js"

[[d1_databases]]
binding = "DB"
database_name = "cerqueira-db-prod"
database_id = "seu-database-id-prod"

# Static assets for large files - exclude cache
[assets]
directory = ".next"
binding = "ASSETS"
exclude = [
  "cache/**/*",
  "**/*.map",
  "server/**/*.js.map",
  "static/chunks/**/*.map"
]