name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          
      - name: Clean up large files for Cloudflare Pages
        run: |
          echo "🧹 Cleaning up large files..."
          
          # Remove webpack cache
          rm -rf .next/cache/webpack
          rm -rf .next/cache/swc
          
          # Remove source maps
          find .next -name "*.map" -type f -delete
          
          # Remove any files larger than 20MB
          find .next -type f -size +20M -delete
          
          # Show remaining large files
          echo "📋 Remaining large files:"
          find .next -type f -size +10M -exec ls -lh {} \; || echo "No large files found"
          
      # Since you're using GitHub integration, Cloudflare will automatically deploy
      # This step is optional - only needed if you want direct API deployment
      - name: Verify build success
        run: |
          echo "✅ Build completed successfully!"
          echo "📁 Build directory contents:"
          ls -la .next/
          echo "📊 Build size:"
          du -sh .next/
          
      # Optional: Deploy directly via API (not needed with GitHub integration)
      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: cerqueira-fullstack
      #     directory: .next
      #     branch: ${{ github.ref_name }}
          
      - name: Deploy cleanup summary
        run: |
          echo "✅ Deployment completed!"
          echo "📊 Final build size:"
          du -sh .next